language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t bitstolearn/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true bitstolearn/docker-react npm run test

deploy:
    edge: true
    provided: elasticbeanstalk
    region: "us-west-1"
    app: "docker-react"
    env: "DockerReact-env"
    bukcet_name: "elasticbeanstalk-us-west-1-482490084455"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
