version: '3'
services:
    web:
        restart: always
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "2000:2000"
        volumes:
            - /usr/app/node_modules
            - .:/usr/app
    tests:
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - /usr/app/node_modules
            - .:/usr/app
        command: ["npm", "run", "test"]